version: '3.9'

services:
  web:
    build: .
    container_name: moodmeals_app
    ports:
      - "8000:8000"
    volumes:
      - ./mood.db:/moodmeals/mood.db  # Mount mood.db directly
    restart: always
