version: '3.9'

services:
  web:
    build: .
    container_name: moodmeals_jenkins_app
    ports:
      - "9000:8000"  # Different host port to avoid conflict
    volumes:
      - .:/moodmeals               # Mount entire code for live updates
      - ./mood.db:/moodmeals/mood.db  # Mount database file
    restart: always
